version: '3'

services:
  redis:
    image: redis
    ports:
      - '63790:6379'

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '54320:5432'

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    stdin_open: true
    env_file:
      - .env
    command: >
      bash -c "python manage.py makemigrations 
      && python manage.py migrate
      && [ -f db_users_data.json ] && python manage.py loaddata db_users_data.json || echo 'db_users_data.json not found'
      && [ -f db_modules_data.json ] && python manage.py loaddata db_modules_data.json || echo 'db_modules_data.json not found'
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    restart: always
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  pg_data:
